#!/bin/bash

# GitHub Repository Setup Script for Daily Culture Bot
# This script helps configure branch protection and CI/CD settings

echo "🔧 Setting up GitHub repository for Daily Culture Bot CI/CD"
echo "=========================================================="

# Check if we're in a git repository
if [ ! -d ".git" ]; then
    echo "❌ Error: Not in a git repository"
    exit 1
fi

# Get repository information
REPO_URL=$(git remote get-url origin)
REPO_NAME=$(basename "$REPO_URL" .git)

echo "📋 Repository: $REPO_NAME"
echo "🔗 URL: $REPO_URL"
echo ""

echo "📝 Manual Setup Instructions:"
echo "============================="
echo ""
echo "1. 🌿 Branch Protection Rules:"
echo "   Go to: https://github.com/$(git config --get remote.origin.url | sed 's/.*github.com[:/]\([^.]*\).*/\1/')/settings/branches"
echo "   - Add rule for 'main' branch"
echo "   - ✅ Require status checks to pass before merging"
echo "   - ✅ Require branches to be up to date before merging"
echo "   - ✅ Require pull request reviews before merging"
echo "   - ✅ Dismiss stale PR approvals when new commits are pushed"
echo "   - ✅ Restrict pushes that create files larger than 100MB"
echo ""
echo "2. 🔐 Required Status Checks:"
echo "   - test (Python 3.11)"
echo "   - pr-validation"
echo "   - build-check"
echo ""
echo "3. 👥 Required Reviewers:"
echo "   - Set to 1 required reviewer"
echo "   - Include yourself as a reviewer"
echo ""
echo "4. 🔒 Additional Settings:"
echo "   - ✅ Require linear history"
echo "   - ✅ Include administrators"
echo "   - ✅ Allow force pushes: ❌ (disabled)"
echo "   - ✅ Allow deletions: ❌ (disabled)"
echo ""
echo "5. 🚀 Workflow Permissions:"
echo "   Go to: https://github.com/$(git config --get remote.origin.url | sed 's/.*github.com[:/]\([^.]*\).*/\1/')/settings/actions"
echo "   - ✅ Allow GitHub Actions to create and approve pull requests"
echo "   - ✅ Allow actions and reusable workflows"
echo ""
echo "6. 🔑 Secrets (Optional - for email/OpenAI integration):"
echo "   Go to: https://github.com/$(git config --get remote.origin.url | sed 's/.*github.com[:/]\([^.]*\).*/\1/')/settings/secrets/actions"
echo "   Add these secrets if you want to test email/OpenAI features:"
echo "   - SMTP_HOST"
echo "   - SMTP_PORT"
echo "   - SMTP_USERNAME"
echo "   - SMTP_PASSWORD"
echo "   - SMTP_FROM_EMAIL"
echo "   - OPENAI_API_KEY"
echo "   - TEST_EMAIL"
echo ""
echo "7. 📊 Code Coverage (Optional):"
echo "   - Sign up for Codecov: https://codecov.io"
echo "   - Connect your repository"
echo "   - Add CODECOV_TOKEN secret if desired"
echo ""
echo "✅ Setup complete! Your CI/CD pipeline is ready."
echo ""
echo "🧪 Test the setup:"
echo "   1. Create a test branch: git checkout -b test-ci"
echo "   2. Make a small change and commit"
echo "   3. Push: git push origin test-ci"
echo "   4. Create a PR from test-ci to main"
echo "   5. Watch the CI/CD pipeline run!"
echo ""
echo "📚 Workflow Files Created:"
echo "   - .github/workflows/ci.yml (Main CI pipeline)"
echo "   - .github/workflows/pr-validation.yml (PR validation)"
echo "   - .github/workflows/release.yml (Release management)"
echo ""
echo "🎯 Next Steps:"
echo "   1. Push this dev branch: git push origin dev"
echo "   2. Follow the manual setup instructions above"
echo "   3. Create a PR from dev to main to test the pipeline"
echo "   4. Merge dev into main when ready"
