name: Daily Culture Email (Manual)

on:
  workflow_dispatch:

jobs:
  send-daily-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Send daily culture email (manual)
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_FROM_EMAIL: ${{ secrets.SMTP_FROM_EMAIL }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python daily_culture_bot.py \
            --complementary \
            --email "$EMAIL_RECIPIENT" \
            --email-format html \
            --max-fame-level 20 \
            --min-match-score 0.3 \
            --candidate-count 6 \
            --vision-candidates 3 \
            --explain-matches
