name: Daily Culture Email

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  send-daily-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Send daily culture email
        env:
          # SMTP Configuration - Set these as GitHub Secrets
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_FROM_EMAIL: ${{ secrets.SMTP_FROM_EMAIL }}
          # Email recipient - Set this as a GitHub Secret
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          # Send complementary artwork and poem via email
          python daily_paintings.py --complementary --email "$EMAIL_RECIPIENT" --email-format both
          
      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: daily-culture-${{ github.run_number }}
          path: |
            artwork_*.json
            poems_*.json
            *.jpg
            *.png
          retention-days: 7
