name: Simple Test

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  test:
    name: Simple Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest -v --tb=short --maxfail=3
        
    - name: Test basic functionality
      run: |
        python daily_culture_bot.py --fast --count 1 --output
        echo "✅ Basic functionality test passed"
